name: 'entsoe_energy'
version: '1.0.0'

profile: 'entsoe_energy'

model-paths: ["dbt_energy/models"]
test-paths: ["dbt_energy/tests"]

models:
  entsoe_energy:
    staging:
      +materialized: view

    marts:
      +materialized: table